# Generated by Django 4.1 on 2023-03-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_debit_note_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_item_voucher',
            old_name='party_account',
            new_name='Particulars',
        ),
    ]
