# Generated by Django 4.1 on 2023-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_rename_party_account_stock_item_voucher_particulars'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_item_voucher',
            name='voucher_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock_item_voucher',
            name='voucher_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
