# Generated by Django 4.1 on 2023-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_bank_transcations_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_item_voucher',
            name='per',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
