# Generated by Django 4.1 on 2023-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0051_stock_itemcreation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='per',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
