# Generated by Django 4.1 on 2023-03-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_alter_stock_itemcreation_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='per',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='quantity',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='rate',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock_itemcreation',
            name='value',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
