# Generated by Django 4.1 on 2023-03-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0056_payment_voucher_company_receipt_voucher_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_transcations',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.companies'),
        ),
    ]
