# Generated by Django 4.1 on 2023-03-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_bank_transcations_bank_recon_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_particulars',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment_particulars',
            name='pay_voucher',
        ),
        migrations.RemoveField(
            model_name='payment_voucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='payment_voucher',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='receipt_particulars',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt_particulars',
            name='rec_voucher',
        ),
        migrations.RemoveField(
            model_name='receipt_voucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt_voucher',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='bank_transcations',
        ),
        migrations.DeleteModel(
            name='payment_particulars',
        ),
        migrations.DeleteModel(
            name='payment_voucher',
        ),
        migrations.DeleteModel(
            name='receipt_particulars',
        ),
        migrations.DeleteModel(
            name='receipt_voucher',
        ),
    ]
