# Generated by Django 4.1 on 2023-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_receipt_voucher_receipt_particulars_payment_voucher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bank_transcations',
            new_name='bank_transactions',
        ),
        migrations.AddField(
            model_name='godown_items',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
